WebApp/Models/AddProjectViewModel.cs
namespace WebApp.Models;

public class AddProjectViewModel
{

}

WebApp/Models/EditProjectViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
namespace WebApp.Models;

public class EditProjectViewModel
{
    public IEnumerable<SelectListItem> Statuses { get; set; } = [];
}

WebApp/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models;

public class LoginViewModel
{
    [Required]
    [DataType(DataType.EmailAddress)]
    [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Please enter a valid email")]
    [Display(Name = "Email", Prompt = "Enter your email")]
    public string Email { get; set; } = null!;

    [Required]
    [DataType(DataType.Password)]
    [RegularExpression(@"^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$", ErrorMessage = "Password must be at least 8 characters long and contain at least one letter and one digit.")]
    [Display(Name = "Password", Prompt = "Enter your password")]
    public string Password { get; set; } = null!;

    public bool RememberMe { get; set; }
}

WebApp/Models/ProjectViewModel.cs
namespace WebApp.Models;

public class ProjectViewModel
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string ProjectTitle { get; set; } = null!;
    public string ClientName { get; set; } = null!;
    public string ProjectDescription { get; set; } = null!;
}

WebApp/Models/ProjectsViewModel.cs
namespace WebApp.Models;

public class ProjectsViewModel
{
    public IEnumerable<ProjectViewModel> Projects { get; set; } = [];
    public AddProjectViewModel AddProjectFormData { get; set; } = new();
    public EditProjectViewModel EditProjectFormData { get; set; } = new();  
}

WebApp/Models/SignUpViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models;

public class SignUpViewModel
{
    [Required]
    [DataType(DataType.Text)]
    [Display(Name = "First Name", Prompt = "Enter your full name")]
    public string FullName { get; set; } = null!;

    [Required]
    [DataType(DataType.EmailAddress)]
    [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Please enter a valid email")]
    [Display(Name = "Email", Prompt = "Enter your email")]
    public string Email { get; set; } = null!;

    [Required]
    [DataType(DataType.Password)]
    [RegularExpression(@"^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$", ErrorMessage = "Password must be at least 8 characters long and contain at least one letter and one digit.")]
    [Display(Name = "Password", Prompt = "Enter your password")]
    public string Password { get; set; } = null!;

    [Required]
    [DataType(DataType.Password)]
    [Compare(nameof(Password), ErrorMessage = "The passwords do not match.")]
    [Display(Name = "Confirm Password", Prompt = "Re-write your password")]
    public string ConfirmPassword { get; set; } = null!;

    [Range(typeof(bool), "true", "true", ErrorMessage ="You must accept the terms... pls we won't sell your soul")]
    public bool AcceptTerms { get; set; }
}

WebApp/Controllers/LogInController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers;

public class LogInController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Index(LoginViewModel model) 
    {
        if (ModelState.IsValid)
        {
            return View(model);
        }

        return View();
    }
}

WebApp/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class ProjectsController : Controller
    {
        [Route("projects")]
        public IActionResult Index()
        {
            var viewModel = new ProjectsViewModel();
            return View(viewModel);
        }
    }
}

WebApp/Controllers/SignUpController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class SignUpController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(SignUpViewModel model)
        {
            if (ModelState.IsValid)
            {
                return View(model);
            }

            return View();
        }
    }
}

WebApp/Views/LogIn/Index.cshtml
@model LoginViewModel

@{
    Layout = "_LoginLayout";
    ViewData["Title"] = "Log In";
}

<div class="card">

    <div class="header-body-wrapper">
        <div class="card-header">
            <h1>Login</h1>
        </div>

        <div class="card-body">
            <form method="post" asp-controller="LogIn" asp-action="Index" novalidate>
            <div class="form-group">
                <label class="form-label" asp-for="Email"></label>
                <input class="form-input" asp-for="Email">
                <span asp-validation-for="Email"></span>
            </div>

            <div class="form-group">
                <label class="form-label" asp-for="Password"></label>
                <input class="form-input" asp-for="Password">
                <span asp-validation-for="Password"></span>
            </div>

            <div class="form-checkbox-group">
                <label class="form-checkbox">
                    <input asp-for="RememberMe" class="form-checkbox-input">Remember me
                </label>
            </div>

            <button type="submit" class="btn">Log In</button>
            </form>
        </div>
    </div>

    <div class="card-footer">
        <p>Don't have an account? <a asp-controller="SignUp" asp-action="Index">Sign Up</a></p>
    </div>

</div>

WebApp/Views/Projects/Index.cshtml
@model ProjectsViewModel

@{
    ViewData["Title"] = "Projects";
}

<div id="projects" class="page">
    <div class="projects-header">
        <h2>Projects</h2>
        <button class="btn add-project-btn" data-type="modal" data-target="#add-project-modal">
            <i class="bi bi-plus"></i>Add Project
        </button>
    </div>

    <nav class="project-tabs">
        <button class="tab active" data-target="#all">ALL</button>
        <button class="tab" data-target="#started">STARTED</button>
        <button class="tab" data-target="#completed">COMPLETED</button>
    </nav>

    <section id="all" class="projects-grid">
        @if (Model.Projects !=null && Model.Projects.Any())
        {
            @foreach(var project in Model.Projects){
                @await Html.PartialAsync("ListItems/_ProjectCardPartial", project)
            }
        }
    </section>

    <section id="started" class="projects-grid hidden">
    </section>

    <section id="completed" class="projects-grid hidden">
    </section>
</div>

@await Html.PartialAsync("Modals/_AddProjectModalPartial", Model.AddProjectFormData)
@await Html.PartialAsync("Modals/_EditProjectModalPartial", Model.EditProjectFormData)

WebApp/Views/Shared/Dropdowns/_ProjectActionsDropdownPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebApp/Views/Shared/Dropdowns/_SettingsDropdownPartial.cshtml
<div id="settings-dropdown" class="dropdown">
    <div class="current-account"><img src="images/user-template.svg">John Doe</div>

    <a href="#" class="btn-logout">
        <img src="images/logout.svg"><p>Log out</p>
    </a>
</div>

WebApp/Views/Shared/ListItems/_ProjectCardPartial.cshtml
@model ProjectViewModel

<div class="project card" data-project-id="@Model.Id">
    <div class="card-header">
        <div class="project-image">
            <img src="images/project-icon.svg" alt="project icon">
        </div>
        <div class="project-info-flex">
            <h6 class="project-title">@Model.ProjectTitle</h6>
            <span class="project-client">@Model.ClientName</span>
        </div>
        <div class="project-actions-container">
            <button type="button" data-type="dropdown" data-target="#project-dropdown-@Model.Id" class="btn-action">
                <i class="bi bi-three-dots"></i>
            </button>
            <div id="project-dropdown-@Model.Id" class="dropdown">
                <nav class="dropdown-options">
                    <button data-type="modal" data-target="#edit-project-modal" class="dropdown-action edit-action">
                        <i class="bi bi-pencil-square"></i>
                        <span>Edit</span>
                    </button>
                </nav>
                <div class="horizontal-divider"></div>
                <nav class="dropdown-options">
                    <button class="dropdown-action edit-action delete">
                        <i class="bi bi-trash3-fill"></i>
                        <span>Delete Project</span>
                    </button>
                </nav>
            </div>
        </div>
    </div>
    <div class="card-body">
        <p>@Html.Raw(Model.ProjectDescription)</p>
    </div>
</div>

WebApp/Views/Shared/Modals/_AddProjectModalPartial.cshtml
@model AddProjectViewModel

<section id="add-project-modal" class="modal">
    <div class="card">
        <div class="card-header">
            <h3>Add Project</h3>
            <button class="btn-close" data-type="close" data-target="#add-project-modal"><img src="images/close.svg" alt="Exit create project"></button>
        </div>

        <div class="card-body">
            <div class="project-upload-icon">
            <img src="images/project-icon.svg">
            </div>

            <form asp-controller="" asp-action="" method="post" enctype="multipart/form-data" novalidate>

                <div class="form-group">
                    <label class="form-label">Project Name</label>
                    <input class="form-input" type="text" placeholder="Project name">
                </div>

                <div class="form-group">
                    <label class="form-label">Client Name</label>
                    <input class="form-input" type="text" placeholder="Client name">
                </div>

                <div class="form-group">
                    <label class="form-label">Project Name</label>
                    <input class="form-input" type="text" placeholder="Project Name">
                </div>

                <div class="form-group">
                    <label class="form-label">Description</label>
                    <div class="text-area-container">
                    <textarea id="add-project-description" class="hide"></textarea>
                    <div id="add-project-editor" class="quill-editor"></div>
                    <div id="add-project-toolbar" class="quill-toolbar">
                        <span class="ql-formats">
                            <button class="ql-bold"></button>
                            <button class="ql-italic"></button>
                            <button class="ql-underline"></button>
                        </span>
                        <span class="ql-formats">
                            <button class="ql-align" value=""></button>
                            <button class="ql-align" value="center"></button>
                            <button class="ql-align" value="right"></button>
                        </span>
                        <span class="ql-formats">
                            <button class="ql-list" value="bullet"></button>
                            <button class="ql-list" value="ordered"></button>
                        </span>
                        <span class="ql-formats">
                            <button class="ql-link" value=""></button>
                        </span>
                    </div>
                    </div>
                </div>

                <div class="form-group-horizontal">
                    <div class="form-group">
                    <label class="form-label">Start Date</label>
                    <input class="form-input" type="date">
                    </div>

                    <div class="form-group">
                    <label class="form-label">End Date</label>
                    <input class="form-input" type="date">
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-label">Budget</label>
                    <div class="form-input-with-icon">
                    <img src="images/dollar.svg">
                    <input class="form-input" type="text" placeholder="0">
                    </div>
                </div>

                <button type="submit" class="btn">Create</button>
            </form>
        </div>
    </div>
</section>

WebApp/Views/Shared/Modals/_EditProjectModalPartial.cshtml
@model EditProjectViewModel

<section id="edit-project-modal" class="modal">
    <div class="card">
        <div class="card-header">
            <h3>Edit Project</h3>
            <button class="btn-close" data-type="close" data-target="#edit-project-modal"><img src="images/close.svg" alt="Exit create project"></button>
        </div>

        <div class="card-body">
            <form asp-controller="" asp-action="" method="post" enctype="multipart/form-data" novalidate>

                <div class="form-group">
                    <label class="form-label">Project Name</label>
                    <input class="form-input" type="text" placeholder="Project name">
                </div>

                <div class="form-group">
                    <label class="form-label">Client Name</label>
                    <input class="form-input" type="text" placeholder="Client name">
                </div>

                <div class="form-group">
                    <label class="form-label">Project Name</label>
                    <input class="form-input" type="text" placeholder="Project Name">
                </div>

                <div class="form-group">
                    <label class="form-label">Description</label>
                    <div class="text-area-container">
                        <textarea id="edit-project-description" class="hide"></textarea>
                        <div id="edit-project-editor" class="quill-editor"></div>
                        <div id="edit-project-toolbar" class="quill-toolbar">
                            <span class="ql-formats">
                                <button class="ql-bold"></button>
                                <button class="ql-italic"></button>
                                <button class="ql-underline"></button>
                            </span>
                            <span class="ql-formats">
                                <button class="ql-align" value=""></button>
                                <button class="ql-align" value="center"></button>
                                <button class="ql-align" value="right"></button>
                            </span>
                            <span class="ql-formats">
                                <button class="ql-list" value="bullet"></button>
                                <button class="ql-list" value="ordered"></button>
                            </span>
                            <span class="ql-formats">
                                <button class="ql-link" value=""></button>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="form-group-horizontal">
                    <div class="form-group">
                        <label class="form-label">Start Date</label>
                        <input class="form-input" type="date">
                    </div>

                    <div class="form-group">
                        <label class="form-label">End Date</label>
                        <input class="form-input" type="date">
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-label">Budget</label>
                    <div class="form-input-with-icon">
                        <img src="images/dollar.svg">
                        <input class="form-input" type="text" placeholder="0">
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-label">Project Satuts</label>
                    <div class="form-select" data-placeholder="Select current status">
                        <button type="button" class="form-select-trigger">
                            <span class="form-select-text"></span><i class="bi bi-three-dots"></i>
                        </button>

                        <ul class="form-select-options">
                            <li class="form-select-option" data-value="started">Started</li>
                            <li class="form-select-option" data-value="finished">Finished</li>
                        </ul>

                        <input type="hidden" name="status-select-value" value="" />
                    </div>
                </div>

                <button type="submit" class="btn">Create</button>
            </form>
        </div>
    </div>
</section>

WebApp/Views/Shared/Partials/_HeaderPartial.cshtml
<header id="main-options">
    <button type="button" class="btn-settings" data-type="dropdown" data-target="#settings-dropdown">
        <img src="images/settings.svg" alt="settings">
    </button>
    @await Html.PartialAsync("Dropdowns/_SettingsDropdownPartial")
    <hr class="vertical-divider">
    <button type="button" class="btn-account">
        <img src="images/user-template.svg" alt="avatar">
    </button>
</header>

WebApp/Views/Shared/Partials/_SidebarPartial.cshtml
<aside id="sidebar">
    <div class="alpha-logo">
        <a href="@Url.Content("~/")">
            <img src="images/alpha-logo.svg">
            <span>alpha</span>
        </a>
    </div>

    <button class="project-btn">
        <a href="#"><img src="images/briefcase.svg" alt="">Projects</a>
    </button>
</aside>

WebApp/Views/Shared/_AuthenticationLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>

    @RenderBody()

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>

            @RenderBody()

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_LogInLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <main>
        <section id="login">
            <div class="center-wrapper">
                @RenderBody()
            </div>
        </section>
    </main>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_ProjectManagementLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>

    <div class="projects-page-wrapper">

        @await Html.PartialAsync("_SidebarPartial")

        <main>
            @await Html.PartialAsync("_MainOptionsPartial")
            @RenderBody()
        </main>
    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_ProjectsLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <script type="importmap"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.js"></script>
    <script src="https://kit.fontawesome.com/beb8ff9a13.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <div class="projects-page-wrapper">
        @await Html.PartialAsync("Partials/_SidebarPartial")
        <main>
            @await Html.PartialAsync("Partials/_HeaderPartial")
        @RenderBody()
        </main>
    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_SignInLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <main>
        <section id="login">
            <div class="center-wrapper">
                @RenderBody()
            </div>
        </section>
    </main>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_SignUpLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <main>
        <section id="signup">
            <div class="center-wrapper">
                @RenderBody()
            </div>
        </section>
    </main>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/SignUp/Index.cshtml
@model SignUpViewModel

@{
    Layout = "_SignUpLayout";
    ViewData["Title"] = "Sign Up";
}

<div class="card">

    <div class="card-header">
        <h1>Create Account</h1>
    </div>

    <div class="card-body">
        <form method="post" asp-controller="SignUp" asp-action="Index" novalidate>
            <div class="form-group">
                <label class="form-label" asp-for="FullName"></label>
                <input class="form-input" asp-for="FullName">
                <span asp-validation-for="FullName"></span>
            </div>

            <div class="form-group">
                <label class="form-label" asp-for="Email"></label>
                <input class="form-input" asp-for="Email">
                <span asp-validation-for="Email"></span>
            </div>

            <div class="form-group">
                <label class="form-label" asp-for="Password"></label>
                <input class="form-input" asp-for="Password">
                <span asp-validation-for="Password"></span>
            </div>

            <div class="form-group">
                <label class="form-label" asp-for="ConfirmPassword"></label>
                <input class="form-input" asp-for="ConfirmPassword">
                <span asp-validation-for="ConfirmPassword"></span>
            </div>

            <div class="form-checkbox-group">
                <label class="form-checkbox">
                    <input asp-for="AcceptTerms" class="form-checkbox-input" /> I accept <a href="#" target="_blank">Terms and Conditions</a>
                    <span class="checkbox-box"></span>
                </label>
            </div>

            <button type="submit" class="btn">Create Account</button>
        </form>
    </div>

    <div class="card-footer">
        <p>Already have an account? <a asp-controller="LogIn" asp-action="Index">Log in</a></p>
    </div>

</div>